# Generated by Django 2.2.2 on 2019-06-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_table.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Tourist_Attraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('prov_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_table.Province')),
            ],
        ),
        migrations.CreateModel(
            name='My_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_table.Tourist_Attraction')),
            ],
        ),
    ]
