# Generated by Django 2.2.2 on 2019-06-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_table',
            name='time',
        ),
        migrations.AlterField(
            model_name='my_table',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
